# Generated by Django 3.1.5 on 2021-05-10 08:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
