# Generated by Django 3.1.5 on 2021-05-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
